[package]
name = "trivial_pr_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
fhe = "0.1.0-beta.4"
fhe-traits = "0.1.0-beta.4"
rand = "0.8.5"
